# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ELEKTRONN - CNN Toolkit
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  A configurable toolkit for 3d/2d Convolutional Neural Networks (CNN). CNNs are used in Machine Learning to make solve difficult classification and regression tasks. ELEKTRONN is written in python and based on theano. It benefits from fast GPU implementations. This toolkit was created by Marius Killinger and Gregor Urban at the Max Planck Institute For Medical Research to solve connectomics tasks.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://elektronn.org" # the base hostname & protocol for your site
github_username: ELEKTRONN

github-url: https://github.com/ELEKTRONN/ELEKTRONN
documentation-url: http://elektronn.github.io/documentation

# Build settings
markdown: kramdown

sass:
  style: :compressed


include:
 - _images
 - _modules
 - _sources
 - _static

navigation:
 - text: Home
   url: /
   icon: ion-android-home
 - text: Getting Started
   url: /getting-started/
   icon: ion-ios-lightbulb
# - text: Use Cases
#   url: /use-cases/
 - text: Development
   url: /development/
   icon: ion-ios-flask
 - text: About
   url: /about/
   icon: ion-ios-people
# - text: Links
#   url: /links/
#   icon: fa-bookmark
